### ISSUE TITLE
app.run is not suitable production microservice deployment

### ISSUE THREAD

**Issue by woosley** [ssola/python-flask-microservice#5]
From Flask document, app.run uses flask internal server is not recommended in production 

```
Flask’s built-in server is not suitable for production as it doesn’t scale well and by default serves only one request at a time. Some of the options available for properly running Flask in production are documented here.
```

I think the sample code using a misleading deployment mechanism here and probabaly should be updated.

**Comment by safwan20** [comment]
may i get to know in which file this error has occured
